const nameToIdMap = new Map();

nameToIdMap.set('inorganic fertilizer',  16901);
nameToIdMap.set('byproduct fertilizer',  16902);
nameToIdMap.set('organic fertilizer',  16903);
nameToIdMap.set('ash timber', 4601);
nameToIdMap.set('maple timber', 4602);
nameToIdMap.set('pine timber', 4603);
nameToIdMap.set('birch timber', 4604);
nameToIdMap.set('log', 4605);
nameToIdMap.set('fir timber', 4606);
nameToIdMap.set('cedar timber', 4607);
nameToIdMap.set('white cedar timber', 4608);
nameToIdMap.set('acacia timber', 4609);
nameToIdMap.set('palm timber', 4610);
nameToIdMap.set('elder tree timber', 4611);
nameToIdMap.set('cactus rind', 4612);
nameToIdMap.set('old tree branch', 4613);
nameToIdMap.set('moss tree timber', 4614);
nameToIdMap.set('loopy tree timber', 4615);
nameToIdMap.set('thuja timber', 4616);
nameToIdMap.set('thornwood timber', 4619);
nameToIdMap.set('snowfield cedar timber', 4621);
nameToIdMap.set('ash plank', 4651);
nameToIdMap.set('ash plywood', 4652);
nameToIdMap.set('sturdy ash plywood', 4653);
nameToIdMap.set('maple plank', 4654);
nameToIdMap.set('maple plywood', 4655);
nameToIdMap.set('sturdy maple plywood', 4656);
nameToIdMap.set('pine plank', 4657);
nameToIdMap.set('pine plywood', 4658);
nameToIdMap.set('sturdy pine plywood', 4659);
nameToIdMap.set('birch plank', 4660);
nameToIdMap.set('birch plywood', 4661);
nameToIdMap.set('sturdy birch plywood', 4662);
nameToIdMap.set('fir plank', 4663);
nameToIdMap.set('fir plywood', 4664);
nameToIdMap.set('sturdy fir plywood', 4665);
nameToIdMap.set('cedar plank', 4666);
nameToIdMap.set('cedar plywood', 4667);
nameToIdMap.set('sturdy cedar plywood', 4668);
nameToIdMap.set('usable scantling', 4669);
nameToIdMap.set('palm plank', 4670);
nameToIdMap.set('palm plywood', 4671);
nameToIdMap.set('sturdy palm plywood', 4672);
nameToIdMap.set('elder tree plank', 4673);
nameToIdMap.set('elder tree plywood', 4674);
nameToIdMap.set('sturdy elder tree plywood', 4675);
nameToIdMap.set('white cedar plank', 4676);
nameToIdMap.set('white cedar plywood', 4677);
nameToIdMap.set('sturdy white cedar plywood', 4678);
nameToIdMap.set('acacia plank', 4680);
nameToIdMap.set('acacia plywood', 4681);
nameToIdMap.set('sturdy acacia plywood', 4682);
nameToIdMap.set('cactus thorn', 4683);
nameToIdMap.set('standardized timber square', 4685);
nameToIdMap.set('sturdy timber square', 4686);
nameToIdMap.set('hard pillar', 4687);
nameToIdMap.set('ship repair material', 4688);
nameToIdMap.set('ship repair kit', 4689);
nameToIdMap.set('pine coated plywood', 4691);
nameToIdMap.set('moss tree plank', 4694);
nameToIdMap.set('moss tree plywood', 4695);
nameToIdMap.set('sturdy moss tree plywood', 4696);
nameToIdMap.set('loopy tree plank', 4697);
nameToIdMap.set('loopy tree plywood', 4698);
nameToIdMap.set('sturdy loopy tree plywood', 4699);
nameToIdMap.set('emergency ship repair kit', 4700);
nameToIdMap.set('thuja plank', 4701);
nameToIdMap.set('thuja plywood', 4702);
nameToIdMap.set('sturdy thuja plywood', 4703);
nameToIdMap.set('thornwood plank', 4710);
nameToIdMap.set('thornwood plywood', 4711);
nameToIdMap.set('sturdy thornwood plywood', 4712);
nameToIdMap.set('snowfield cedar plank', 4721);
nameToIdMap.set('snowfield cedar plywood', 4722);
nameToIdMap.set('sturdy snowfield cedar plywood', 4723);
nameToIdMap.set('ash sap', 5001);
nameToIdMap.set('maple sap', 5002);
nameToIdMap.set('pine sap', 5003);
nameToIdMap.set('birch sap', 5004);
nameToIdMap.set('bloody tree knot', 5005);
nameToIdMap.set('spirit\'s leaf', 5006);
nameToIdMap.set('monk\'s branch', 5007);
nameToIdMap.set('old tree bark', 5008);
nameToIdMap.set('fir sap', 5009);
nameToIdMap.set('cedar sap', 5010);
nameToIdMap.set('red tree lump', 5011);
nameToIdMap.set('white cedar sap', 5012);
nameToIdMap.set('acacia sap', 5013);
nameToIdMap.set('elder tree sap', 5014);
nameToIdMap.set('palm sap', 5015);
nameToIdMap.set('cactus sap', 5016);
nameToIdMap.set('moss tree sap', 5017);
nameToIdMap.set('loopy tree sap', 5018);
nameToIdMap.set('dead tree essence', 5019);
nameToIdMap.set('thuja sap', 5020);
nameToIdMap.set('thornwood sap', 5023);
nameToIdMap.set('snowfield cedar sap', 5024);
nameToIdMap.set('sunrise herb', 5401);
nameToIdMap.set('silver azalea', 5402);
nameToIdMap.set('fire flake flower', 5403);
nameToIdMap.set('dry mane grass', 5404);
nameToIdMap.set('silk honey grass', 5405);
nameToIdMap.set('everlasting herb', 5406);
nameToIdMap.set('fortune teller mushroom', 5407);
nameToIdMap.set('arrow mushroom', 5408);
nameToIdMap.set('dwarf mushroom', 5409);
nameToIdMap.set('cloud mushroom', 5410);
nameToIdMap.set('sky mushroom', 5411);
nameToIdMap.set('tiger mushroom', 5412);
nameToIdMap.set('emperor mushroom', 5413);
nameToIdMap.set('ghost mushroom', 5414);
nameToIdMap.set('fog mushroom', 5415);
nameToIdMap.set('hump mushroom', 5416);
nameToIdMap.set('bluffer mushroom', 5417);
nameToIdMap.set('ancient mushroom', 5418);
nameToIdMap.set('amanita mushroom', 5419);
nameToIdMap.set('truffle mushroom', 5420);
nameToIdMap.set('pile of sunrise herbs', 5421);
nameToIdMap.set('bunch of silver azaleas', 5422);
nameToIdMap.set('bunch of fire flake flowers', 5423);
nameToIdMap.set('bunch of dry mane grass', 5424);
nameToIdMap.set('bunch of silk honey grass', 5425);
nameToIdMap.set('big fortune teller mushroom', 5426);
nameToIdMap.set('big arrow mushroom', 5427);
nameToIdMap.set('big dwarf mushroom', 5428);
nameToIdMap.set('big cloud mushroom', 5429);
nameToIdMap.set('big sky mushroom', 5430);
nameToIdMap.set('big tiger mushroom', 5431);
nameToIdMap.set('big emperor mushroom', 5432);
nameToIdMap.set('big ghost mushroom', 5433);
nameToIdMap.set('big fog mushroom', 5434);
nameToIdMap.set('big hump mushroom', 5435);
nameToIdMap.set('big bluffer mushroom', 5436);
nameToIdMap.set('big ancient mushroom', 5437);
nameToIdMap.set('big amanita mushroom', 5438);
nameToIdMap.set('wild grass', 5439);
nameToIdMap.set('insectivore plant flower', 5440);
nameToIdMap.set('insectivore plant leaf', 5441);
nameToIdMap.set('insectivore plant stalk', 5442);
nameToIdMap.set('insectivore plant root', 5443);
nameToIdMap.set('high-quality sunrise herb', 5444);
nameToIdMap.set('high-quality silver azalea', 5445);
nameToIdMap.set('high-quality fire flake flower', 5446);
nameToIdMap.set('high-quality dry mane grass', 5447);
nameToIdMap.set('high-quality silk honey grass', 5448);
nameToIdMap.set('high-quality fortune teller mushroom', 5450);
nameToIdMap.set('high-quality arrow mushroom', 5451);
nameToIdMap.set('high-quality dwarf mushroom', 5452);
nameToIdMap.set('high-quality cloud mushroom', 5453);
nameToIdMap.set('high-quality sky mushroom', 5454);
nameToIdMap.set('high-quality tiger mushroom', 5455);
nameToIdMap.set('high-quality emperor mushroom', 5456);
nameToIdMap.set('high-quality ghost mushroom', 5457);
nameToIdMap.set('high-quality fog mushroom', 5458);
nameToIdMap.set('high-quality hump mushroom', 5459);
nameToIdMap.set('high-quality bluffer mushroom', 5460);
nameToIdMap.set('high-quality ancient mushroom', 5461);
nameToIdMap.set('high-quality amanita mushroom', 5462);
nameToIdMap.set('special sunrise herb', 5464);
nameToIdMap.set('special silver azalea', 5465);
nameToIdMap.set('special fire flake flower', 5466);
nameToIdMap.set('special dry mane grass', 5467);
nameToIdMap.set('special silk honey grass', 5468);
nameToIdMap.set('special fortune teller mushroom', 5470);
nameToIdMap.set('special arrow mushroom', 5471);
nameToIdMap.set('special dwarf mushroom', 5472);
nameToIdMap.set('special cloud mushroom', 5473);
nameToIdMap.set('special sky mushroom', 5474);
nameToIdMap.set('special tiger mushroom', 5475);
nameToIdMap.set('special emperor mushroom', 5476);
nameToIdMap.set('special ghost mushroom', 5477);
nameToIdMap.set('special fog mushroom', 5478);
nameToIdMap.set('special hump mushroom', 5479);
nameToIdMap.set('special bluffer mushroom', 5480);
nameToIdMap.set('special ancient mushroom', 5481);
nameToIdMap.set('special amanita mushroom', 5482);
nameToIdMap.set('nolina', 5484);
nameToIdMap.set('penestraria', 5485);
nameToIdMap.set('dalvenia alrea', 5486);
nameToIdMap.set('toxic watermelon', 5487);
nameToIdMap.set('glossy bone piece', 5488);
nameToIdMap.set('bouquet mushroom', 5489);
nameToIdMap.set('leccinum', 5490);
nameToIdMap.set('purple mushroom', 5491);
nameToIdMap.set('pie mushroom', 5492);
nameToIdMap.set('eyelash cup', 5493);
nameToIdMap.set('star anise mushroom', 5494);
nameToIdMap.set('desert herb', 5495);
nameToIdMap.set('high-quality nolina', 5496);
nameToIdMap.set('high-quality penestraria', 5497);
nameToIdMap.set('high-quality dalvenia alrea', 5498);
nameToIdMap.set('high-quality bouquet mushroom', 5499);
nameToIdMap.set('high-quality leccinum', 5500);
nameToIdMap.set('high-quality purple mushroom', 5501);
nameToIdMap.set('high-quality pie mushroom', 5502);
nameToIdMap.set('special nolina', 5503);
nameToIdMap.set('special penestraria', 5504);
nameToIdMap.set('special dalvenia alrea', 5505);
nameToIdMap.set('special bouquet mushroom', 5506);
nameToIdMap.set('special leccinum', 5507);
nameToIdMap.set('special purple mushroom', 5508);
nameToIdMap.set('special pie mushroom', 5509);
nameToIdMap.set('rainbow button mushroom', 5515);
nameToIdMap.set('blue umbrella mushroom', 5516);
nameToIdMap.set('volcanic umbrella mushroom', 5517);
nameToIdMap.set('pink trumpet mushroom', 5518);
nameToIdMap.set('white umbrella mushroom', 5519);
nameToIdMap.set('green pendulous mushroom', 5520);
nameToIdMap.set('white flower mushroom', 5521);
nameToIdMap.set('vedelona', 5522);
nameToIdMap.set('purple pink flower', 5523);
nameToIdMap.set('yellow flower', 5524);
nameToIdMap.set('sky blue flower', 5525);
nameToIdMap.set('violet flower', 5526);
nameToIdMap.set('blue flower', 5527);
nameToIdMap.set('audria', 5528);
nameToIdMap.set('saffron', 5529);
nameToIdMap.set('hazel tree fruit', 5530);
nameToIdMap.set('mimosa stalk', 5531);
nameToIdMap.set('bracken', 5532);
nameToIdMap.set('high-quality delotia', 5536);
nameToIdMap.set('special delotia', 5537);
nameToIdMap.set('delotia', 5538);
nameToIdMap.set('chanterelle', 5544);
nameToIdMap.set('red-spotted amanita', 5546);
nameToIdMap.set('mesima', 5548);
nameToIdMap.set('dictyophora', 5550);
nameToIdMap.set('high-quality chanterelle', 5552);
nameToIdMap.set('special chanterelle', 5553);
nameToIdMap.set('high-quality red-spotted amanita', 5554);
nameToIdMap.set('special red-spotted amanita', 5555);
nameToIdMap.set('high-quality mesima', 5556);
nameToIdMap.set('special mesima', 5557);
nameToIdMap.set('high-quality dictyophora', 5558);
nameToIdMap.set('special dictyophora', 5559);
nameToIdMap.set('weeds', 5600);
nameToIdMap.set('scarlet rosebay', 820101);
nameToIdMap.set('pink rosebay', 820102);
nameToIdMap.set('goosefoot leaf', 820104);
nameToIdMap.set('tigerflower', 820107);
nameToIdMap.set('youngji mushroom', 820109);
nameToIdMap.set('maehwa', 820131);
nameToIdMap.set('viola', 820136);
nameToIdMap.set('bamboo sprout', 820145);
nameToIdMap.set('white truffle mushroom', 820909);
export default nameToIdMap;